version: 1.0.0
name: CATSMS – Recursive Time-Series Engine for AI/ML
description: Domain-agnostic, infinite feature chaining for FinTech, Industry 4.0, and cross-domain AI platforms.
url: https://piotr1959.github.io
repository: https://github.com/piotr1959/piotr1959.github.io
site_branch: master
timezone: Europe/Berlin

# Remove or update these if you don't use them
twitter:
  username: piotrdzierzanowski

# Update these if you have your own assets
logo: "/img/logo-catsms.svg"
google_analytics_id: 
google_site_verification: 
cloudinary_url: 

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
- scope:
    path: ''
  values:
    image: "/img/catsms-og.png"

future: true

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

feed:
  categories:
  - release

kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
    math_engine: mathjax

sass:
  style: compressed

strict_front_matter: true

exclude:
- icomoon-selection.json
- readme.md